#+OPTIONS: ^:{}
#+STARTUP: indent nolineimages nofold
#+TITLE: irnb(i ruby note book) or org ruby note book
#+AUTHOR: 関西学院大学・理工学部・情報科学科　西谷滋人 2018
#+EMAIL:     (concat "nishitani@kwansei.ac.jp")
#+LANGUAGE:  jp
#+OPTIONS:   H:4 toc:t num:2

#+SETUPFILE: /Users/bob/Github/org-html-themes/setup/theme-readtheorg-local-daddygongon.setup

* Irnb
ipynbみたいにnotebookをorg+rubyで容易に作成できるsystem

** background

文書作成は規模の小さいうちはいいが大きくなるにつれて破綻する．
それは，毎週のレポートでもそうだし，さらに学期末試験や卒業論文に
なったら悲惨．

それらをうまく乗り越えるには，小さい時と大きくなった時で，
文書やdirectoryが相似形になっているフラクタル構造が理想的．
そうすれば規模が大きくなっても対応できるという安心感があるから．
どのような粒度の知識であろうと，学習の最初から構造化されたノートを
提供しようというのがirnbの理想．そしてstageの進化をsupportしてくれる．．．

gemspecは面白い役割を持ったfileかも．
規模が大きくなって下に増やしていく時にはpercpectiveがわかりやすいが，
上に付け足す，あるいは下に入る時にはそれらを統括する箇所，
本でいうところの章の概要みたいなものかな．．．
でもそれはREADME.orgだな．．．
上へのlinkはdirectoryで管理できないから．

末枝と主枝だけは違う構造だな．
だって，main branchのREADME.orgはtocだろうし，
末枝はfirststage的構造だろうから．

** Installation
Add this line to your application's Gemfile:

#+BEGIN_SRC ruby
    gem 'irnb'
#+END_SRC

And then execute:

#+BEGIN_EXAMPLE
    $ bundle
#+END_EXAMPLE

Or install it yourself as:

#+BEGIN_EXAMPLE
    $ gem install irnb
#+END_EXAMPLE

** Usage


** Development
   :PROPERTIES:
   :CUSTOM_ID: development
   :END:

After checking out the repo, run =bin/setup= to install dependencies.
Then, run =rake test= to run the tests. You can also run =bin/console=
for an interactive prompt that will allow you to experiment.

To install this gem onto your local machine, run
=bundle exec rake install=. To release a new version, update the version
number in =version.rb=, and then run =bundle exec rake release=, which
will create a git tag for the version, push git commits and tags, and
push the =.gem= file to [[https://rubygems.org][rubygems.org]].

** Contributing
   :PROPERTIES:
   :CUSTOM_ID: contributing
   :END:

Bug reports and pull requests are welcome on GitHub at
https://github.com/[USERNAME]/irnb. This project is intended to be a
safe, welcoming space for collaboration, and contributors are expected
to adhere to the [[http://contributor-covenant.org][Contributor
Covenant]] code of conduct.

** License
   :PROPERTIES:
   :CUSTOM_ID: license
   :END:

The gem is available as open source under the terms of the
[[https://opensource.org/licenses/MIT][MIT License]].

** Code of Conduct
   :PROPERTIES:
   :CUSTOM_ID: code-of-conduct
   :END:

Everyone interacting in the Irnb project's codebases, issue trackers,
chat rooms and mailing lists is expected to follow the
[[https://github.com/%5BUSERNAME%5D/irnb/blob/master/CODE_OF_CONDUCT.md][code
of conduct]].
