#!/usr/bin/env ruby
require 'colorize'
def http_link(m)
  print 'http link:'.green
  p m
end
def file_link(m)
  print 'file link:'.green
  if File.exists?(m[1])
    puts m[1].green
  else
    puts m[1].red
    puts File.basename(m[1]).red
  end
end
file = ARGV[0] || 'README.org'

m = []
File.readlines(file).each do |line|
  http_link(m) if m = line.match(/\[\[(.+)\]\[(.+)\]\]/)
  file_link(m) if m = line.match(/\[\[file:(.+)\]\]/)
end

