#!/usr/bin/env ruby
require 'colorize'
require 'thor'
require 'fileutils'
require "ornb"

module Ornb
  class CLI < Thor
    def initialize(*argv)
      super(*argv)
    end

    desc 'readme', 'make initial README.org'
    def readme(*argv)
      lib = File.expand_path("../../lib", __FILE__)
      p s_file = File.join(lib, 'readme', 'README.org')
      p Dir.entries('.')
      if File.exists?('./README.org')
        puts "README.org exists. "
      else
        FileUtils.cp(s_file, '.')
      end
    end

    desc 'plot', 'cp gnuplot.rake'
    def plot(*argv)
      lib = File.expand_path("../../lib", __FILE__)
      target = 'gnuplot.rake'
      p s_file = File.join(lib, File.basename(target,'.rake'), target)
      p Dir.entries('.')
      if File.exists?(target)
        puts target + " exists. "
      else
        FileUtils.cp(s_file, '.')
      end
    end

    desc 'platex', 'cp platex.rake'
    def platex(*argv)
      lib = File.expand_path("../../lib", __FILE__)
      target = 'platex.rake'
      p s_file = File.join(lib, File.basename(target,'.rake'), target)
      p Dir.entries('.')
      if File.exists?(target)
        puts target + " exists. "
      else
        FileUtils.cp(s_file, '.')
      end
    end

    desc 'tree', 'tree display'
    def tree(*argv)
      system 'rm -f *~ *# #*'
      file = argv[0] || '.'
      $deep_level = argv[1].to_i || 2
      cont =  print_dir(file, 0, '')
      print "\n\n"+cont+"\n"
    end

    desc 'link_check', 'link check'
    def link_check(*argv)
      file = argv[0] || 'README.org'
      puts "target_file: "+file
      File.readlines(file).each_with_index do |line, i|
        line.scan(/\[\[(.+?)\]\]/) do |match|
          p match
          link = (m = match[0].match(/(.+)\]\[/) )? m[1] : match[0].to_s
          unless File.exists?(link)
            next if link.match(/^\#/)
            printf("%4d:%s:",i,link)
            printf("%s\n",line.chomp)
            search_file(link)
          end
        end
      end
    end

    private

    def print_dir(file,level,cont)
      level += 1
      return "- [[#{file}]]\n" if level > $deep_level
      print "*"*level+" #{file}\n"
      dir = File.join(file,"*")
      Dir.glob(dir).each do |file|
        case File.ftype(file)
        when 'link', 'file'
          cont << "- [[#{file}]]\n"
        when 'directory'
          print print_dir(file,level,'')
        end
      end
      cont
    end

    def search_file(link)
      p file = File.basename(link)
      system "find . -name #{file}"
    end


  end
end

Ornb::CLI.start(ARGV)
